export const string = {
  monthly: 'Monthly',
  yearly: 'Yearly',
  quarterly: 'Quarterly',
  upgradeToPro: 'Upgrade to Pro',
  monthlyPrice: '$4.99',
  fourMonthlyPrice: '$12.99',
  yearlyPrice: '$44.99',
  tryMusic: 'Try Music',
  pro: 'Pro',
  accessUnlimited: 'Get access for unlimited songs',
  unlockAccess: 'Unlimited songs access',
  checkMarkOne: 'High audio quality',
  checkMarkTwo: 'Ad-free audio streaming',
  checkMarkThree: 'Enjoy every track with full access',
  proUnlocked:
    'Pro Unlocked!\n 🎧 Ad-free music and more await.\n Let the beats roll!',
  musicZone: 'Enter Music Zone',
  musicAccess: 'Music',
};
